FROM postgres:latest
ENV POSTGRES_USER valetappuser
ENV POSTGRES_PASSWORD Test123*
ENV POSTGRES_DB valetappDB
COPY createDB.sql /Users/solladev/Documents/Projects/valet-app-spring/src/main/resources/docker/createDB.sql
EXPOSE 5432